// <auto-generated />
using System;
using Cerebotani.GabrieleTagliani.Soccer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cerebotani.GabrieleTagliani.Soccer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260223081142_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Cerebotani.GabrieleTagliani.Soccer.Models.Campionato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fine")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Inizio")
                        .HasColumnType("TEXT");

                    b.Property<int>("StagioneId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StagioneId");

                    b.ToTable("Campionati");
                });

            modelBuilder.Entity("Cerebotani.GabrieleTagliani.Soccer.Models.Squadra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Citta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Stadio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Squadre");
                });

            modelBuilder.Entity("Cerebotani.GabrieleTagliani.Soccer.Models.SquadraCampionato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CampionatiId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SquadreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CampionatiId");

                    b.HasIndex("SquadreId");

                    b.ToTable("SquadreCampionati");
                });

            modelBuilder.Entity("Cerebotani.GabrieleTagliani.Soccer.Models.Stagione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stagioni");
                });

            modelBuilder.Entity("Cerebotani.GabrieleTagliani.Soccer.Models.Campionato", b =>
                {
                    b.HasOne("Cerebotani.GabrieleTagliani.Soccer.Models.Stagione", "Stagione")
                        .WithMany("Campionati")
                        .HasForeignKey("StagioneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stagione");
                });

            modelBuilder.Entity("Cerebotani.GabrieleTagliani.Soccer.Models.SquadraCampionato", b =>
                {
                    b.HasOne("Cerebotani.GabrieleTagliani.Soccer.Models.Campionato", "Campionati")
                        .WithMany("SquadreCampionato")
                        .HasForeignKey("CampionatiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cerebotani.GabrieleTagliani.Soccer.Models.Squadra", "Squadre")
                        .WithMany()
                        .HasForeignKey("SquadreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campionati");

                    b.Navigation("Squadre");
                });

            modelBuilder.Entity("Cerebotani.GabrieleTagliani.Soccer.Models.Campionato", b =>
                {
                    b.Navigation("SquadreCampionato");
                });

            modelBuilder.Entity("Cerebotani.GabrieleTagliani.Soccer.Models.Stagione", b =>
                {
                    b.Navigation("Campionati");
                });
#pragma warning restore 612, 618
        }
    }
}
